version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ctwOtCIwuXmctrZFMezTBQCJuBnTmDks
    ports:
      - "20570:20570"
